### ISSUE TITLE
Extension fails to load properly

### ISSUE THREAD

**Issue by Obspogon** [uwx/PlayniteSteamLikeLastActivity#1]
![image](https://user-images.githubusercontent.com/72287594/200537191-80efbe59-2e2f-4a3a-b97b-3c86d0323b05.png)

Win 10, Playnite 10.3

**Comment by uwx** [comment]
Make sure [.NET 4.8](https://dotnet.microsoft.com/en-us/download/dotnet-framework/thank-you/net48-web-installer) is installed. Also, a lot of your extensions appear to not be loading properly. This could mean Playnite data is corrupted. Try reinstalling the extension.

**Comment by Obspogon** [comment]
reinstalling them fixed all the extensions
